### ISSUE TITLE
Adapt canvas to resolution

### ISSUE THREAD

**Issue by VJ-Duardo** [VJ-Duardo/CoronaSnake#1]
Right now the canvas size is hard coded for a resolution of 1920x1080, which leads to the game field being cut off if using a smaller resolution. The canvas should adapt to the resolution so that its always completely visible.

**Comment by 20Koen02** [comment]
Working on it.

**Comment by 20Koen02** [comment]
Please add the "hacktoberfest" topic to the repo before merging https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by VJ-Duardo** [comment]
nice, thank you
